# Generated by Django 4.2.2 on 2023-07-12 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField(unique=True)),
                ('employee_name', models.CharField(max_length=30)),
                ('company', models.CharField(default='SolarEdge', max_length=30)),
                ('position', models.CharField(default='QA_automation_engineer', max_length=30)),
                ('employment_type', models.CharField(choices=[('Full_time', 'Full_time'), ('Part_time', 'Part_time')], max_length=30)),
                ('staff', models.CharField(choices=[('Production', 'Production'), ('Operation', 'Operation'), ('Sales', 'Sales'), ('Finance', 'Finance')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(auto_now_add=True)),
                ('checkIn_time', models.DateTimeField(auto_now_add=True)),
                ('checkOut_time', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracker.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(auto_now_add=True)),
                ('check_time', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracker.employee')),
            ],
        ),
    ]
