# Generated by Django 4.2.2 on 2023-06-09 19:02

from django.db import migrations, models
import time_tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('check_date', models.DateField(auto_now_add=True)),
                ('check_time', models.DateTimeField(auto_now_add=True)),
                ('QR_code', models.ImageField(upload_to='')),
            ],
        ),
    ]
