# Generated by Django 4.2.2 on 2023-06-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0003_alter_check_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(auto_now_add=True)),
                ('check_time', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(upload_to='media')),
                ('employee_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Check',
        ),
    ]
