# Generated by Django 4.1.7 on 2023-06-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0004_checks_delete_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIn_date', models.DateField(auto_now_add=True)),
                ('checkIn_time', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkOut_date', models.DateField(auto_now_add=True)),
                ('checkOut_time', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.IntegerField()),
            ],
        ),
    ]
